# Generated by Django 5.2.4 on 2025-07-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('end_date', models.DateField(auto_now=True)),
                ('manager', models.ManyToManyField(to='employees.employee')),
            ],
        ),
    ]
