# Generated by Django 5.2.4 on 2025-07-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
