# Generated by Django 5.2.4 on 2025-07-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Customer',
            new_name='customer',
        ),
    ]
