# Generated by Django 5.2.4 on 2025-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_orders_product_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer',
            new_name='Customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(to='accounts.product'),
        ),
    ]
