# Generated by Django 5.2.4 on 2025-07-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_orders_product_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date_created',
            new_name='date_ordered',
        ),
    ]
